# Generated by Django 5.2.8 on 2025-11-21 04:24

import subject_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0013_alter_student_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(unique=True, validators=[subject_app.validators.validate_subject_name])),
                ('professor', models.CharField(validators=[subject_app.validators.validate_professor_name])),
                ('students', models.ManyToManyField(related_name='subjects', to='student_app.student')),
            ],
        ),
    ]
