# Generated by Django 5.2.8 on 2025-11-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lock_number',
            new_name='locker_number',
        ),
    ]
