# Generated by Django 5.2.8 on 2025-11-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0009_alter_student_locker_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='12-12-12'),
        ),
    ]
