# Generated by Django 5.2.8 on 2025-11-21 01:36

import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_alter_student_locker_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(validators=[student_app.validators.validate_name]),
        ),
    ]
