# Generated by Django 5.2.8 on 2025-11-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0013_alter_student_student_email'),
        ('subject_app', '0002_remove_subject_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='subject_app.subject'),
        ),
    ]
